import PermissionStrings from './permissions';
import roles from './roles';

const { ADMIN, BEACH_ADMIN, USER } = roles;
const {
  CAN_VIEW_USER,
  CAN_UPDATE_USER,
  CAN_DELETE_USER,

  CAN_VIEW_BEACH,
  CAN_CREATE_BEACH,
  CAN_UPDATE_BEACH,
  CAN_DELETE_BEACH,

  CAN_VIEW_ROLE,
  CAN_CREATE_ROLE,
  CAN_UPDATE_ROLE,
  CAN_DELETE_ROLE,

  CAN_VIEW_FLAG,
  CAN_CREATE_FLAG,
  CAN_UPDATE_FLAG,
  CAN_DELETE_FLAG,

  CAN_VIEW_USER_BEACH,
  CAN_CREATE_USER_BEACH,
  CAN_UPDATE_USER_BEACH,
  CAN_DELETE_USER_BEACH,
} = PermissionStrings;

export const rolesPermissionsMap = {
  [CAN_VIEW_USER]: [BEACH_ADMIN, USER],
  [CAN_UPDATE_USER]: [ADMIN, BEACH_ADMIN],
  [CAN_DELETE_USER]: [ADMIN, BEACH_ADMIN],

  [CAN_VIEW_BEACH]: [ADMIN, BEACH_ADMIN, USER],
  [CAN_CREATE_BEACH]: [ADMIN, BEACH_ADMIN],
  [CAN_UPDATE_BEACH]: [ADMIN, BEACH_ADMIN],
  [CAN_DELETE_BEACH]: [ADMIN, BEACH_ADMIN],

  [CAN_VIEW_ROLE]: [ADMIN, BEACH_ADMIN, USER],
  [CAN_CREATE_ROLE]: [ADMIN, BEACH_ADMIN],
  [CAN_UPDATE_ROLE]: [ADMIN, BEACH_ADMIN],
  [CAN_DELETE_ROLE]: [ADMIN, BEACH_ADMIN],

  [CAN_VIEW_FLAG]: [ADMIN, BEACH_ADMIN, USER],
  [CAN_CREATE_FLAG]: [ADMIN, BEACH_ADMIN],
  [CAN_UPDATE_FLAG]: [ADMIN, BEACH_ADMIN],
  [CAN_DELETE_FLAG]: [ADMIN, BEACH_ADMIN],

  [CAN_VIEW_USER_BEACH]: [ADMIN, BEACH_ADMIN, USER],
  [CAN_CREATE_USER_BEACH]: [ADMIN, BEACH_ADMIN],
  [CAN_UPDATE_USER_BEACH]: [ADMIN, BEACH_ADMIN],
  [CAN_DELETE_USER_BEACH]: [ADMIN, BEACH_ADMIN],
};
export type Permission = PermissionStrings;
